---
title: "Spatial_Analysis_DataExploration"
author: "Bella Huang, Cecilia Liang, Isabella Yang, Michelle Du"
date: "2025-12-11"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# 1. Set up
```{r setup, include=FALSE}
# Set your working directory
library(here)
here()

# Load your packages
library(tidyverse)
library(lubridate)
library(dplyr)

# Packages for Time Series Analysis
library(trend)
library(zoo)

# Packages for Spatial Analysis
library(RColorBrewer)
library(sf)
library(leaflet)
library(mapview); mapviewOptions(fgb = FALSE)

# Set your ggplot theme
my_theme <- theme_minimal() +
  theme(
    # text
    plot.title = element_text(face = "bold", hjust = 0.5, size = 14),
    axis.title.y = element_text(size = 12, margin = margin(r = 8)),
    axis.text = element_text(size = 10),
    # lines & grids
    axis.ticks = element_line(linewidth = 0.3),
    panel.grid.major = element_line(linewidth = 0.2, linetype = "dashed", color = "grey75"),
    panel.grid.minor = element_blank(),
    # backgrounds
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = "grey85"),
    legend.key = element_rect(fill = "white", color = NA),
)

theme_set(my_theme)

# Load data (cleaned)
egrid2018 <- read.csv(here("Data/Processed/Spatial_analysis/egrid2018_clean.csv"), stringsAsFactors = TRUE)
egrid2019 <- read.csv(here("Data/Processed/Spatial_analysis/egrid2019_clean.csv"), stringsAsFactors = TRUE)
egrid2020 <- read.csv(here("Data/Processed/Spatial_analysis/egrid2020_clean.csv"), stringsAsFactors = TRUE)
egrid2021 <- read.csv(here("Data/Processed/Spatial_analysis/egrid2021_clean.csv"), stringsAsFactors = TRUE)
egrid2022 <- read.csv(here("Data/Processed/Spatial_analysis/egrid2022_clean.csv"), stringsAsFactors = TRUE)
egrid2023 <- read.csv(here("Data/Processed/Spatial_analysis/egrid2023_clean.csv"), stringsAsFactors = TRUE)
```

# 2. Load Counties Shapefile
```{r, counties shapefile}
# Read in all US counties shapefile into an sf dataframe
US_counties_sf <- read_sf(here("Data/Spatial/cb_2018_us_county_20m.shp")) 
st_crs(US_counties_sf)
mapview(US_counties_sf)
```

# 3. Convert dataframe to a spatial features ("sf")
```{r, convert df to sf}
egrid2018_sf <- egrid2018 %>%
  st_as_sf(coords = c('Plant.longitude', 'Plant.latitude'), crs = 4269, remove = FALSE)

str(egrid2018_sf)

egrid2019_sf <- egrid2019 %>%
  st_as_sf(coords = c('Plant.longitude', 'Plant.latitude'), crs = 4269, remove = FALSE)

str(egrid2019_sf)

egrid2020_sf <- egrid2020 %>%
  st_as_sf(coords = c('Plant.longitude', 'Plant.latitude'), crs = 4269, remove = FALSE)

str(egrid2020_sf)

egrid2021_sf <- egrid2021 %>%
  st_as_sf(coords = c('Plant.longitude', 'Plant.latitude'), crs = 4269, remove = FALSE)

str(egrid2021_sf)

egrid2022_sf <- egrid2022 %>%
  st_as_sf(coords = c('Plant.longitude', 'Plant.latitude'), crs = 4269, remove = FALSE)

str(egrid2022_sf)

egrid2023_sf <- egrid2023 %>%
  st_as_sf(coords = c('Plant.longitude', 'Plant.latitude'), crs = 4269, remove = FALSE)

str(egrid2023_sf)
```


# 4. Map Electricity Plants Locations
1. 2018 Electricity Plants Locations
```{r, Mainland USA}
ggplot() +
  geom_sf(data = US_counties_sf,
          fill = "grey90",
          color = "grey50") +
  geom_sf(data = egrid2018_sf,
          color = "darkblue",
          size = 0.3) +
  coord_sf(
    xlim = c(-125, -65), 
    ylim = c(24, 50)
    ) +
  labs(
    title = "2018 Electricity Plants-Mainland USA",
    x = "Longitude",
    y = "Latitude"
  ) +
  my_theme
```

```{r, Alaska}
ggplot() +
  geom_sf(data = US_counties_sf,
          fill = "grey90",
          color = "grey50") +
  geom_sf(data = egrid2018_sf,
          color = "darkblue",
          size = 1) +
  coord_sf(
    xlim = c(-179, -130),
    ylim = c(51, 72) 
    ) +
  labs(
    title = "2018 Electricity Plants-Alaska",
    x = "Longitude",
    y = "Latitude"
  ) +
  my_theme
```


```{r, Hawaii}
ggplot() +
  geom_sf(data = US_counties_sf,
          fill = "grey90",
          color = "grey50") +
  geom_sf(data = egrid2018_sf,
          color = "darkblue",
          size = 1) +
  coord_sf(
    xlim = c(-160.5, -154.5),
    ylim = c(18.5, 22.5) 
    ) +
  labs(
    title = "2018 Electricity Plants-Hawaii",
    x = "Longitude",
    y = "Latitude"
  ) +
  my_theme
```

2. 2019 Electrivity Plants Locations
```{r, Mainland USA}
ggplot() +
  geom_sf(data = US_counties_sf,
          fill = "grey90",
          color = "grey50") +
  geom_sf(data = egrid2019_sf,
          color = "darkblue",
          size = 0.3) +
  coord_sf(
    xlim = c(-125, -65), 
    ylim = c(24, 50)
    ) +
  labs(
    title = "2019 Electricity Plants-Mainland USA",
    x = "Longitude",
    y = "Latitude"
  ) +
  my_theme
```

```{r, Alaska}
ggplot() +
  geom_sf(data = US_counties_sf,
          fill = "grey90",
          color = "grey50") +
  geom_sf(data = egrid2019_sf,
          color = "darkblue",
          size = 1) +
  coord_sf(
    xlim = c(-179, -130),
    ylim = c(51, 72) 
    ) +
  labs(
    title = "2019 Electricity Plants-Alaska",
    x = "Longitude",
    y = "Latitude"
  ) +
  my_theme
```

```{r, Hawaii}
ggplot() +
  geom_sf(data = US_counties_sf,
          fill = "grey90",
          color = "grey50") +
  geom_sf(data = egrid2019_sf,
          color = "darkblue",
          size = 1) +
  coord_sf(
    xlim = c(-160.5, -154.5),
    ylim = c(18.5, 22.5) 
    ) +
  labs(
    title = "2019 Electricity Plants-Hawaii",
    x = "Longitude",
    y = "Latitude"
  ) +
  my_theme
```


... same format, do more if needed

# 4. Catogorized Electricity Plant
```{r, Mainland USA}
ggplot() +
  geom_sf(data = US_counties_sf,
          fill  = "grey90",
          color = "grey70") +
  geom_sf(data = egrid2018_sf,
          aes(color = Plant.primary.coal.oil.gas..other.fossil.fuel.category),
          size  = 0.6,
          alpha = 0.8) +
  coord_sf(xlim = c(-125, -65), ylim = c(24, 50)) + 
  scale_color_brewer(
    palette = "Paired", 
    name    = "Primary fuel type"
  ) +
  guides(color = guide_legend(
    override.aes = list(size = 5) 
  )) +
  labs(
    title    = "2018 Electricity Plants by Primary Fuel Type-Mainland USA",
    x        = "Longitude",
    y        = "Latitude"
  ) +
  theme_minimal() +
  theme(legend.position = "right")

```

```{r, Alaska}
ggplot() +
  geom_sf(data = US_counties_sf,
          fill  = "grey90",
          color = "grey70") +
  geom_sf(data = egrid2018_sf,
          aes(color = Plant.primary.coal.oil.gas..other.fossil.fuel.category),
          size  = 0.6,
          alpha = 0.8) +
  coord_sf(xlim = c(-160.5, -154.5), ylim = c(51, 72)) +
  scale_color_brewer(
    palette = "Paired", 
    name    = "Primary fuel type"
  ) +
  guides(color = guide_legend(
    override.aes = list(size = 5) 
  )) +
  labs(
    title    = "2018 Electricity Plants by Primary Fuel Type-Alaska",
    x        = "Longitude",
    y        = "Latitude"
  ) +
  theme_minimal() +
  theme(legend.position = "right")

```

```{r, Hawaii}
ggplot() +
  geom_sf(data = US_counties_sf,
          fill  = "grey90",
          color = "grey70") +
  geom_sf(data = egrid2018_sf,
          aes(color = Plant.primary.coal.oil.gas..other.fossil.fuel.category),
          size  = 0.6,
          alpha = 0.8) +
  coord_sf(xlim = c(-160.5, -154.5), ylim = c(18.5, 22.5)) +
  scale_color_brewer(
    palette = "Paired", 
    name    = "Primary fuel type"
  ) +
  guides(color = guide_legend(
    override.aes = list(size = 5) 
  )) +
  labs(
    title    = "2018 Electricity Plants by Primary Fuel Type-Hawaii",
    x        = "Longitude",
    y        = "Latitude"
  ) +
  theme_minimal() +
  theme(legend.position = "right")

```

... same format, do more if needed

# 5. Map the pattern of number of unit/generator
```{r}
mapview(US_counties_sf,
        col.regions = "gray90",
        color = "gray50",
        layer.name = "Counties") +
  mapview(egrid2018_sf,
          zcol = "Number.of.units", 
          cex = 4,              
          alpha = 0.9,
          layer.name = "Number of Generator")
```

